language: generic
addons:
  homebrew:
    packages:
      - pyenv
matrix:
  include:
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7"

before_install:
  - .build/install_pyenv.sh

install:
  - pip install -U pip
  - pip install -U -r ci_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest -v

after_success:
  - python -m coverage report --show-missing
  - codecov

notifications:
  slack:
    secure: "Rqp8yM8fjDgS+Oi+/0fHWqEg9ABAmIyOP7dkcF/tSQ3nEi+jzDD69VxFYfOLXDq/h5Tn38bNTUWIsvZnu46M+bsK+equhdXjhsBH1QXERnR6VxWC0R90IGUomj2I2Dl65NzHRkngt7MqNeGuDc7CttbMqAfchHh7AmEDlC93g/UL8Iyv7MDxDhX/o+Zfjl01woGhhLhlnGE+LiAmoORDPWdqkRDaMKPmmFDyXLNOS1jO+JvOtLRYgZ2T+5KON/ut45G4x2kUkMEzg6p1k+D1bxpRq30tF2kKqTjxSXYLcvuApn7jupJIgKvC+B/Nzq6ac5ipbhTYfgTrPy1JryX69BGFZRosuk2Gh+flmpWMJ6QJv6Q2VQZ7zZzYbNe2JLsGh5XVy1vKxitZD7GxM05Uy4iG98EbSJ+cBt3a6riuoX/68AclBHQpF753LGUaPGCrwZk3M/YUUea99uTLIOYQy2eV3KxEX1QWnGDrbBzrEVjf5lNA2F+Autq8QTdDZqcoqAexyPgPOfQhK6GsoX7oUStCoJnQNDH2W9TJQMp2kInwqSObfL75QDBqnLIk0Xdgut2D6gxr/+s36MjU0MFwfJto/p3lGT/wpDOi7oIgU2cEpg5jHb5uwicJahlNDmxUmSnQ4LkCxZneWoYB3FeNuFG8JGZPbB1fv9G8/gUDHNM="
  email: false
