name: actions

on:
  push:
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install -r requirements_ci.txt
      - run: python -m coverage run --branch --source . -m unittest -v
      - run: python -m coverage report --show-missing
      - run: codecov
